datasource:
  driver-class: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/onesync
  username: root
  password: 123456
  size: 2


synchronize:

  # 玩家背包及末影箱
  inventory: true

  # 玩家持久化数据 PersistentDataContainer(PDC)
  pdc: false

  # 玩家档案: 游戏模式, 是否 OP, 生命值, 最大生命值, 经验值, 饥饿值
  profile:
    game-mode: false
    op: false
    health: false
    exp: false
    food: false
