version: 2

datasource:
  driver-class: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/onesync
  username: root
  password: 123456
  size: 2

# 是否打印调试日志
debug: true

# 服务器 ID
# 如果配置了这项, 那么在服务器重启的时候能自动解锁因为异常关闭而锁住的玩家
# 注意 1: 要么别配置, 如果配置就一定不能重复!!!
# 注意 2: 因为服务器异常关闭的锁定, 可能导致玩家的数据不是最新的!!!
server-id: ''

synchronize:

  # 玩家背包
  inventory: true

  # 末影箱
  ender-chest: true

  # 玩家持久化数据 PersistentDataContainer(PDC)
  pdc: false

  # 玩家成就数据
  advancements: false

  # 效果, 如药水效果、Buff
  potion-effects: false

  # 经济, 对 Vault 插件的支持
  vault: false

  # 玩家档案
  profile:

    # 游戏模式
    game-mode: false

    # 是否 OP
    op: false

    # 生命值, 最大生命值
    health: false

    # 经验
    exp: false

    # 饥饿值, 饱食度, 饥饿度
    food: false

    # 氧气值
    air: false

snapshot:

  # 每位玩家最大快照数量
  capacity: 45

  # 多少天内必须至少保存一份最后的快照
  keep-days: 7

    # 何时保存玩家快照
    # 除了这里可以指定的节点以外, 玩家退出游戏, 服务器关闭也会保存快照
    # 可选值:
    # WORLD_SAVE              : (全体) 保存地图时触发, 约 5 分钟一次, 经测试 50 名玩家约 400 ms
    # PLAYER_DEATH            : (个人) 玩家死亡时触发, 适合死亡掉落的服务器
  # PLAYER_GAME_MODE_CHANGE : (个人) 玩家游戏模式切换
  when:
    - WORLD_SAVE
    - PLAYER_GAME_MODE_CHANGE