name: OneSync
version: '${project.version}'
main: io.github.hello09x.onesync.Main
api-version: '1.20'
folia-supported: true


depend:
  - CommandAPI
  - ProtocolLib

softdepend:
  - Vault

libraries:
  - com.mysql:mysql-connector-j:8.1.0